### ISSUE TITLE
Uses django.conf.urls.defaults, removed in Django 1.6

### ISSUE THREAD

**Issue by OdyX** [pinax/pinax-boxes#3]
[django.conf.urls.defaults got removed in Django 1.6](https://docs.djangoproject.com/en/1.6/internals/deprecation/#id1), and [symposion uses django-boxes now](https://github.com/pinax/symposion/commit/ba0bb84ad70b45be40ccaacb353b5bbf46c65b34), but it [depends on Django 1.7](https://github.com/pinax/symposion/blob/ba0bb84ad70b45be40ccaacb353b5bbf46c65b34/requirements/base.txt#L1)

**Comment by paltman** [comment]
Done
